### ISSUE TITLE
--no-sandbox is not being detected

### ISSUE THREAD

**Issue by chrisothemis** [tobilen/storybook-addon-storypa11y#29]
I'm trying to run a test with storypa11y and I get this error:

```
● Storypa11y › Framewürk/Origami Examples/o-video › Multiple Sizes

    Expected file:///app/dist/storybook-static/iframe.html?id=framew%C3%BCrk-origami-examples-o-video--multiple-sizes&viewMode=story to be accessible, but:
    Error: Failed to launch chrome!
    [1119/110453.438028:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

      at node_modules/storybook-addon-storypa11y/src/test-bodies.ts:21:22
      at step (node_modules/storybook-addon-storypa11y/dist/test-bodies.js:33:23)
      at Object.next (node_modules/storybook-addon-storypa11y/dist/test-bodies.js:14:53)
      at node_modules/storybook-addon-storypa11y/dist/test-bodies.js:8:71
      at Object.<anonymous>.__awaiter (node_modules/storybook-addon-storypa11y/dist/test-bodies.js:4:12)
      at pa11y (node_modules/storybook-addon-storypa11y/dist/test-bodies.js:42:12)
      at node_modules/storybook-addon-storypa11y/src/api/index.ts:26:11
      at step (node_modules/storybook-addon-storypa11y/dist/api/index.js:44:23)
      at Object.next (node_modules/storybook-addon-storypa11y/dist/api/index.js:25:53)
      at node_modules/storybook-addon-storypa11y/dist/api/index.js:19:71
      at Object.<anonymous>.__awaiter (node_modules/storybook-addon-storypa11y/dist/api/index.js:15:12)
      at testBody (node_modules/storybook-addon-storypa11y/src/api/index.ts:24:52)
      at node_modules/storybook-addon-storypa11y/node_modules/@storybook/addon-storyshots-puppeteer/dist/ts3.9/puppeteerTest.js:95:50
      at step (node_modules/storybook-addon-storypa11y/node_modules/@storybook/addon-storyshots-puppeteer/dist/ts3.9/puppeteerTest.js:44:23)
      at Object.next (node_modules/storybook-addon-storypa11y/node_modules/@storybook/addon-storyshots-puppeteer/dist/ts3.9/puppeteerTest.js:25:53)
      at fulfilled (node_modules/storybook-addon-storypa11y/node_modules/@storybook/addon-storyshots-puppeteer/dist/ts3.9/puppeteerTest.js:16:58)
          at runMicrotasks (<anonymous>)
```
          

My test file, storypa11y.test.js, looks like this:

```
import { initStorypa11y } from 'storybook-addon-storypa11y';

initStorypa11y({
    out: "dist/storybook-static",
    pa11yOptions: {
        includeNotices: false,
        includeWarnings: false,
        chromeLaunchConfig: {
            args: ['--no-sandbox']
        } 
    }
});
```

**Comment by tobilen** [comment]
Hey @chrisothemis,

you're right, the launch options were not passed through to puppeteer. I fixed this in https://github.com/tobilen/storybook-addon-storypa11y/commit/1807ced31e9931a9bba6c9ea5afee8a5c7038ff5, please update to `2.1.1` and give it a try.

I am bit confused though because the underlying `storyshots-puppeteer` addon already sets `no-sandbox` by default, see https://github.com/storybookjs/storybook/blob/master/addons/storyshots/storyshots-puppeteer/src/puppeteerTest.ts#L81
